export const colors = [
	"bg-red-100",
	"bg-yellow-100",
	"bg-green-100",
	"bg-blue-100",
	"bg-indigo-100",
	"bg-purple-100",
	"bg-pink-100",
	"bg-cyan-100",
	"bg-rose-100",
	"bg-fuchsia-100",
	"bg-violet-100",
	"bg-lightBlue-100",
];

export const sprintBoardData = [
	{
		id: 1,
		name: "To Do",
		done: 0,
		order: 512,
		issues: [
			{
				id: 132,
				key: 90,
				name: "FE-Fixes Bug in Edit part of Lesson in admin side(redux part error)",
				issueType: "story",
				storyPoint: 0,
				statusOrder: {
					order: 1536,
				},
				epic: null,
				assignee: {
					id: 20,
					fullName: "Bishal Bista",
					image: "https://picsum.photos/200",
				},
				attachments: [],
				color: colors[Math.floor(Math.random() * colors.length)],
			},
			{
				id: 131,
				key: 89,
				name: "UI/UX- Design for Uploading Assignments from admin side",
				issueType: "story",
				storyPoint: 0,
				statusOrder: {
					order: 1792,
				},
				epic: null,
				assignee: {
					id: 909,
					fullName: "Rikesh",
					image: "https://picsum.photos/200",
				},
				attachments: [],
				color: colors[Math.floor(Math.random() * colors.length)],
			},
			{
				id: 173,
				key: 95,
				name: "UI/UX- Design for Admin Assignment Page",
				issueType: "story",
				storyPoint: 0,
				statusOrder: {
					order: 2048,
				},
				epic: null,
				assignee: {
					id: 909,
					fullName: "Rikesh",
					image: "https://picsum.photos/200",
				},
				attachments: [],
				color: colors[Math.floor(Math.random() * colors.length)],
			},
			{
				id: 178,
				key: 96,
				name: "List of Issues - 9 October  ",
				issueType: "bug",
				storyPoint: 0,
				statusOrder: {
					order: 2560,
				},
				epic: null,
				assignee: {
					id: 20,
					fullName: "Bishal Bista",
					image: null,
				},
				attachments: [],
				color: colors[Math.floor(Math.random() * colors.length)],
			},
			{
				id: 183,
				key: 99,
				name: "FE-Design for assignment in admin side",
				issueType: "story",
				storyPoint: 0,
				statusOrder: {
					order: 3072,
				},
				epic: null,
				assignee: {
					id: 36,
					fullName: "Satis Kumar Chaudhary",
					image: "https://picsum.photos/200",
				},
				attachments: [],
				color: colors[Math.floor(Math.random() * colors.length)],
			},
		],
	},
	{
		id: 2,
		name: "In Progress",
		done: 0,
		order: 896,
		issues: [],
	},
	{
		id: 4,
		name: "Testing",
		done: 0,
		order: 1280,
		issues: [
			{
				id: 169,
				key: 94,
				name: "BE - Lesson not showing issue in the external course API",
				issueType: "bug",
				storyPoint: 0,
				statusOrder: {
					order: -512,
				},
				epic: null,
				assignee: {
					id: 11,
					fullName: "Sandeep Sharma",
					image: "https://picsum.photos/200",
				},
				attachments: [],
				color: colors[Math.floor(Math.random() * colors.length)],
			},
			{
				id: 133,
				key: 91,
				name: "BE- API for Upload Assignment",
				issueType: "story",
				storyPoint: 0,
				statusOrder: {
					order: 0,
				},
				epic: null,
				assignee: {
					id: 11,
					fullName: "Sandeep Sharma",
					image: "https://picsum.photos/200",
				},
				attachments: [],
				color: colors[Math.floor(Math.random() * colors.length)],
			},
			{
				id: 179,
				key: 97,
				name: "BE - Progress being 100 before completion of all the lessons",
				issueType: "bug",
				storyPoint: 0,
				statusOrder: {
					order: 1024,
				},
				epic: null,
				assignee: {
					id: 11,
					fullName: "Sandeep Sharma",
					image: "https://picsum.photos/200",
				},
				attachments: [],
				color: colors[Math.floor(Math.random() * colors.length)],
			},
			{
				id: 180,
				key: 98,
				name: "BE - Calculation of progress after addition of new lesson or deletion of existing lesson ",
				issueType: "story",
				storyPoint: 0,
				statusOrder: {
					order: 1536,
				},
				epic: null,
				assignee: {
					id: 11,
					fullName: "Sandeep Sharma",
					image: "https://picsum.photos/200",
				},
				attachments: [],
				color: colors[Math.floor(Math.random() * colors.length)],
			},
			{
				id: 186,
				key: 100,
				name: "BE - Course count is different in learnEd and scholars and video with text lesson not showing in learnEd",
				issueType: "bug",
				storyPoint: 0,
				statusOrder: {
					order: 2048,
				},
				epic: null,
				assignee: {
					id: 11,
					fullName: "Sandeep Sharma",
					image: "https://picsum.photos/200",
				},
				attachments: [],
				color: colors[Math.floor(Math.random() * colors.length)],
			},
			{
				id: 187,
				key: 101,
				name: "BE - Lesson added in Scholars not showing in LearnEd due to sync command issue",
				issueType: "bug",
				storyPoint: 0,
				statusOrder: {
					order: 2560,
				},
				epic: null,
				assignee: {
					id: 11,
					fullName: "Sandeep Sharma",
					image: "https://picsum.photos/200",
				},
				attachments: [],
				color: colors[Math.floor(Math.random() * colors.length)],
			},
			{
				id: 188,
				key: 102,
				name: "BE - Attachment url should accept both url and file when updating lesson",
				issueType: "bug",
				storyPoint: 0,
				statusOrder: {
					order: 3072,
				},
				epic: null,
				assignee: {
					id: 11,
					fullName: "Sandeep Sharma",
					image: "https://picsum.photos/200",
				},
				attachments: [],
				color: colors[Math.floor(Math.random() * colors.length)],
			},
		],
	},
	{
		id: 3,
		name: "Done",
		done: 1,
		order: 1536,
		issues: [
			{
				id: 158,
				key: 93,
				name: "BE - Lesson not saved in database after success message",
				issueType: "bug",
				storyPoint: 0,
				statusOrder: {
					order: -512,
				},
				epic: null,
				assignee: {
					id: 11,
					fullName: "Sandeep Sharma",
					image: "https://picsum.photos/200",
				},
				attachments: [],
				color: colors[Math.floor(Math.random() * colors.length)],
			},
		],
	},
];
